In [145]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [146]:
data=pd.read_csv("https://raw.githubusercontent.com/sunnysavita10/credit_card_pw_hindi/main/creditCardFraud_28011964_120214.csv")

In [147]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   LIMIT_BAL                   1001 non-null   int64
 1   SEX                         1001 non-null   int64
 2   EDUCATION                   1001 non-null   int64
 3   MARRIAGE                    1001 non-null   int64
 4   AGE                         1001 non-null   int64
 5   PAY_0                       1001 non-null   int64
 6   PAY_2                       1001 non-null   int64
 7   PAY_3                       1001 non-null   int64
 8   PAY_4                       1001 non-null   int64
 9   PAY_5                       1001 non-null   int64
 10  PAY_6                       1001 non-null   int64
 11  BILL_AMT1                   1001 non-null   int64
 12  BILL_AMT2                   1001 non-null   int64
 13  BILL_AMT3                   1001 non-null   int64
 14  BILL_AMT

In [148]:
data['EDUCATION'].unique()

array([2, 1, 3, 5, 4, 6], dtype=int64)

In [149]:
data['SEX'].unique()

array([1, 2], dtype=int64)

In [150]:
data['default payment next month'].unique()

array([0, 1], dtype=int64)

In [151]:
data['MARRIAGE'].unique()

array([1, 2, 3, 0], dtype=int64)

In [152]:
cat_columns=['SEX','MARRIAGE','EDUCATION']

In [153]:
X=data.drop(labels=['default payment next month'],axis=1)

In [154]:
X.head()

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0      50000    1          2         1   57     -1      0     -1      0   
1      50000    1          1         2   37      0      0      0      0   
2     500000    1          1         2   29      0      0      0      0   
3     100000    2          2         2   23      0     -1     -1      0   
4     140000    2          3         1   28      0      0      2      0   

   PAY_5  ...  BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0      0  ...      35835      20940      19146      19131      2000     36681   
1      0  ...      57608      19394      19619      20024      2500      1815   
2      0  ...     445007     542653     483003     473944     55000     40000   
3      0  ...        601        221       -159        567       380       601   
4      0  ...      12108      12211      11793       3719      3329         0   

   PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  
0     10000      9000       689       679  
1       657      1000      1000       800  
2     38000     20239     13750     13770  
3         0       581      1687      1542  
4       432      1000      1000      1000  

[5 rows x 23 columns]

In [155]:
y=data['default payment next month']

In [156]:
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
num_cols=[]
for i in X.columns:
    if i not in cat_columns:
        num_cols.append(i)

In [157]:
num_pipeline=Pipeline(
    steps=[
   ('imputer',SimpleImputer(strategy='median')),
   ('scaler',StandardScaler())
   ]
)
cat_pipeline=Pipeline(
    steps=[
        ('impute',SimpleImputer(strategy='most_frequent')),
        ('scaler',StandardScaler())
    ]
)
preprocessor=ColumnTransformer([
    ('num_pipeline',num_pipeline,num_cols),
    ('cat_pipeline',cat_pipeline,cat_columns)

]
)



In [158]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.30,random_state=20)

In [159]:
X_train=pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [160]:
X_train

num_pipeline__LIMIT_BAL  num_pipeline__AGE  num_pipeline__PAY_0  \
0                   0.502113          -0.867328             0.880409   
1                   0.345377          -0.543122             1.736362   
2                   2.618038           1.294044             0.024456   
3                  -0.124828          -0.759259             0.024456   
4                  -0.830137          -0.867328             1.736362   
..                       ...                ...                  ...   
695                 0.110274           0.105290            -1.687450   
696                -1.143608           0.213358             0.024456   
697                -0.751769           0.105290             0.024456   
698                 2.618038           0.321427            -0.831497   
699                 0.737215          -0.110848            -0.831497   

     num_pipeline__PAY_2  num_pipeline__PAY_3  num_pipeline__PAY_4  \
0               1.759753             0.143052             0.273558   
1              -0.647727            -0.645423            -0.573746   
2               0.154767             0.143052             0.273558   
3               0.154767             0.143052             0.273558   
4               0.154767             0.143052             0.273558   
..                   ...                  ...                  ...   
695            -1.450220            -1.433898            -1.421049   
696             0.154767             0.143052             0.273558   
697             0.154767             0.143052             0.273558   
698             1.759753            -0.645423            -0.573746   
699            -0.647727            -0.645423            -0.573746   

     num_pipeline__PAY_5  num_pipeline__PAY_6  num_pipeline__BILL_AMT1  \
0               0.253159             0.288640                -0.479176   
1              -0.590705            -0.536046                -0.672631   
2               0.253159             0.288640                 0.139538   
3               0.253159             0.288640                 0.793230   
4               1.940886             0.288640                -0.392970   
..                   ...                  ...                      ...   
695            -1.434568            -1.360732                -0.521592   
696             0.253159             0.288640                -0.438844   
697             0.253159             0.288640                 0.317205   
698            -0.590705             0.288640                -0.668290   
699            -0.590705            -0.536046                 0.041638   

     num_pipeline__BILL_AMT2  ...  num_pipeline__BILL_AMT6  \
0                  -0.482781  ...                -0.490679   
1                  -0.662819  ...                -0.503856   
2                   0.945755  ...                 0.556293   
3                   0.818459  ...                 0.985417   
4                  -0.370504  ...                -0.203871   
..                       ...  ...                      ...   
695                -0.358109  ...                -0.285669   
696                -0.426438  ...                -0.263440   
697                 0.340681  ...                -0.329323   
698                -0.662819  ...                -0.565067   
699                -0.662951  ...                -0.567628   

     num_pipeline__PAY_AMT1  num_pipeline__PAY_AMT2  num_pipeline__PAY_AMT3  \
0                 -0.415937               -0.291812               -0.345263   
1                 -0.394196               -0.284441               -0.174446   
2                  4.657633                1.980868                2.375393   
3                 -0.126060               -0.061541               -0.070502   
4                 -0.318683               -0.245261               -0.200202   
..                      ...                     ...                     ...   
695                1.120193                0.551686                3.333882   
696               -0.299334      

In [161]:
from sklearn.ensemble import RandomForestClassifier
random=RandomForestClassifier()

In [162]:
random.fit(X_train,Y_train)

RandomForestClassifier()

In [163]:
Y_pred=random.predict(X_test)

In [164]:
from sklearn.metrics import accuracy_score

In [165]:
Y_test

891    0
694    0
798    0
147    0
859    0
      ..
591    0
377    1
939    1
57     0
140    0
Name: default payment next month, Length: 301, dtype: int64

In [166]:
print(accuracy_score(Y_test,Y_pred))

0.840531561461794


In [167]:
from sklearn.linear_model import LogisticRegression

In [168]:
from sklearn.ensemble import Xgboost

In [170]:
from sklearn.ensemble import GradientBoostingClassifier
gb=GradientBoostingClassifier()

In [171]:
gb.fit(X_train,Y_train)
Y_pred1=gb.predict(X_test)
print(accuracy_score(Y_test,Y_pred1))

0.8172757475083057
